FROM nvidia/cudagl:11.3.1-devel-ubuntu20.04
MAINTAINER Samyakh Tukra <samyakh.tukra17@himperial.ac.uk>

ENV DEBIAN_FRONTEND noninteractive


# Install some basic utilities
RUN apt-get update && apt-get install -y \
    curl \
    ca-certificates \
    sudo \
    git \
    bzip2 \
    libx11-6 \
 && rm -rf /var/lib/apt/lists/*



####### CREATE A USER #########
RUN useradd --create-home --groups sudo --shell /bin/bash newuser \
	&& chown -R newuser: /home/newuser
RUN mkdir -p /etc/sudoers.d \
    && echo "newuser ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/newuser \
        && chmod 0440 /etc/sudoers.d/newuser


# environment, dependencies and entry points
USER newuser
ENV HOME /home/newuser/
WORKDIR /home/newuser/surg_t/
RUN chmod 777 /home/newuser

# Set up the Conda environment
ENV CONDA_AUTO_UPDATE_CONDA=false \
    PATH=/home/newuser/miniconda/bin:$PATH
COPY surg_t_requirements.yml /home/newuser/surg_t/docker/surg_t_requirements.yml



USER root

RUN curl -sLo ~/miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-py39_4.10.3-Linux-x86_64.sh 
RUN chmod +x ~/miniconda.sh 
RUN ~/miniconda.sh -b -p ~/miniconda 
RUN rm ~/miniconda.sh 
RUN conda env update -n base -f /home/newuser/surg_t/docker/surg_t_requirements.yml 
RUN conda clean -ya
RUN pip3 install jupyter

USER newuser
ENV HOME /home/newuser/
WORKDIR /home/newuser/surg_t/
RUN chmod 777 /home/newuser